# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_SONATA_ADMIN

        ROLE_BROKER:
            - ROLE_USER
            - ROLE_SONATA_ADMIN
            - ROLE_ADMIN_CUSTOMER_VIEW
            - ROLE_ADMIN_CUSTOMER_LIST
            - ROLE_ADMIN_CUSTOMER_EDIT
            - ROLE_ADMIN_CUSTOMER_CREATE
            - ROLE_ADMIN_TRANSACTION_CREATE
            - ROLE_ADMIN_TRANSACTION_LIST
            - ROLE_ADMIN_TRANSACTION_VIEW
            - ROLE_ADMIN_CUSTOMER_NOTE_CREATE

        ROLE_RETENTION: ROLE_BROKER
        ROLE_CONVERSION: ROLE_BROKER

        ROLE_EXPERT:
            - ROLE_BROKER
            - ROLE_SONATA_ADMIN
            - ROLE_ADMIN_CUSTOMER_EDIT

        ROLE_MANAGER:
            - ROLE_BROKER
            - ROLE_ADMIN_CUSTOMER_EDIT
            - ROLE_SONATA_ADMIN
            - ROLE_ADMIN_TRANSACTION_EDIT
            - ROLE_ADMIN_ANNOUNCEMENT_CREATE
            - ROLE_ADMIN_ANNOUNCEMENT_VIEW
            - ROLE_ADMIN_ANNOUNCEMENT_LIST

        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_SONATA_ADMIN]

        ROLE_TOP_MANAGER:
            - ROLE_USER
            - ROLE_SONATA_ADMIN
            - ROLE_ADMIN_CUSTOMER_VIEW
            - ROLE_ADMIN_CUSTOMER_LIST
            - ROLE_ADMIN_CUSTOMER_EDIT
            - ROLE_ADMIN_ANNOUNCEMENT_CREATE
            - ROLE_ADMIN_ANNOUNCEMENT_VIEW
            - ROLE_ADMIN_ANNOUNCEMENT_LIST

        ROLE_ACCOUNTANT:
            - ROLE_USER
            - ROLE_SONATA_ADMIN
            - ROLE_ADMIN_USER_VIEW
            - ROLE_ADMIN_USER_LIST
            - ROLE_ADMIN_USER_EDIT
            - ROLE_ADMIN_BRAND_VIEW
            - ROLE_ADMIN_BRAND_LIST
            - ROLE_ADMIN_BRAND_EDIT

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email



    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:
                path:   /logout
                target: /admin

            anonymous:    true
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/salary-report/\d+, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/finalize-monthly-report-preview/\d+, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, roles: [ROLE_BROKER, ROLE_ADMIN, ROLE_MANAGER, ROLE_TOP_MANAGER, ROLE_ACCOUNTANT] }
